version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petservice_marketplace
      MYSQL_USER: petuser
      MYSQL_PASSWORD: petpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: petservice_marketplace
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/petservice_marketplace?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: concept-jwt-secret-key-for-demo-only
      JWT_REFRESH_SECRET: concept-refresh-secret-key-for-demo-only
      CORS_ORIGIN: http://localhost:5000
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000:5000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
